name: Scala CI

on:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: failed step
        run: |
          exit 1
      - name: Send mail
        if: failure()
        uses: mvn/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: sunilbadboy24@gmail.com
          password: 9441611842
          subject: Github Actions job result
          body: Build job of ${{github.repository}} Failed!
          to: vamshi5590@gmail.com
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
            java-version: 1.8
      - name: Run tests
        run: mvn clean install
